#!/bin/bash

exec-mpc() {
    mpc $* &> /dev/null
}

case $BLOCK_BUTTON in
  1) exec-mpc toggle ;;
  2) exec-mpc stop   ;;
  3) showname=$((!$showname)); echo $showname > $SHOWNAME_PATH ;;
  4) exec-mpc prev    ;;
  5) exec-mpc next   ;;
esac

playing="▶ "
paused="⏸ "
stopped="⏹ Nothing to play :("

status=$(mpc status | sed -n 's/^\[\([^])]*\)\].*$/\1/p')
song=$(mpc current | awk -F ' - ' '{printf "%s", substr($2, 0, 20)}')

case $status in
  playing) echo "$playing$song" ;;
  paused)  echo "$paused$song"  ;;
  *)       echo "$stopped$song" ;;
esac
